//! Kafka specific Types.
//!
//! The data described here is usually generated by wrapping or converting the "raw" data
//! we get back from querying the Kafka cluster metadata.

mod broker;
mod topic_partitions_status;

pub use broker::Broker;
pub use topic_partitions_status::{PartitionStatus, TopicPartitionsStatus};
